<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
    use Symbiote\GridFieldExtensions\GridFieldEditableColumns;
    use UndefinedOffset\SortableGridField\Forms\GridFieldSortableRows;

    class Page extends SiteTree
    {
        private static $db = [
            'PageTheme' => 'Enum(array("dark","light"))',
        ];

        private static $has_one = [
            'PageBanner' => Image::class
        ];

        private static $owns = [
            'PageBanner',
        ];

        private static $has_many = [
            'Sections' => Section::class
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName(['Content']);
            $fields->addFieldToTab('Root.Main', UploadField::create('PageBanner')
                ->setFolderName('PageBanner')
                ->setDescription('For individual page banner use only otherwise go to settings.'),'Metadata');
            $fields->addFieldToTab('Root.Main', DropdownField::create('PageTheme', 'Page theme',
                $this->dbObject('PageTheme')->enumValues()),'Metadata');

            $gridConfig = GridFieldConfig_RecordEditor::create(9999);
            if ($this->owner->Sections()->Count()) {
                $gridConfig->addComponent(new GridFieldSortableRows('Sort'));
            }

            $gridConfig->addComponent(new GridFieldEditableColumns());
            $gridColumns = $gridConfig->getComponentByType(GridFieldEditableColumns::class);
            $gridColumns->setDisplayFields([
                'Width' => [
                    'title' => 'Width',
                    'callback' => function($record, $column, $grid) {
                        $fields = DropdownField::create($column, $column, array(
                            'col-lg-2' => '16%',
                            'col-lg-3' => '25%',
                            'col-lg-4' => '33%',
                            'col-lg-5' => '41%',
                            'col-lg-6' => '50%',
                            'col-lg-7' => '58%',
                            'col-lg-8' => '66%',
                            'col-lg-9' => '75%',
                            'col-lg-10' => '83%',
                            'col-lg-11' => '91%',
                            'col-lg-12' => '100%',
                        ));
                        return $fields;
                    }
                ],
                'Archived' => [
                    'title' => 'Archive',
                    'callback' => function($record, $column, $grid) {
                        return CheckboxField::create($column);
                    }
                ]
            ]);

            $gridField = GridField::create(
                'Sections',
                'Sections',
                $this->owner->Sections(),
                $gridConfig
            );

            $fields->addFieldToTab('Root.Main', $gridField, 'Metadata');

            return $fields;
        }

        public function getVisibleSections()
        {
            return $this->Sections()->filter('Archived', false)->sort('Sort');
        }
    }
}
