<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\FieldGroup;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class EventYear extends DataObject
    {
        private static $default_sort  = 'Sort';

        private static $singular_name = "Event Year";
        private static $plural_name = "Event Years";

        private static $db = [
            'Name'     => 'Text',
            'ShowInFinalistsPage' => 'Boolean',
            'FinalistsPageContent'=> 'HTMLText',
            'ShowInWinnersPage'   => 'Boolean',
            'WinnersPageContent'  => 'HTMLText',
            'ShowInGalleryPage'   => 'Boolean',
            'GalleryPageContent'  => 'HTMLText',
            'Archived' => 'Boolean',
            'Sort'     => 'Int',
        ];

        private static $summary_fields = [
            'Name',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Extra', FieldGroup::create(
                CheckboxField::create('ShowInFinalistsPage')
                    ->setDescription('Click to show in Finalists Page accordion'),
                HTMLEditorField::create('FinalistsPageContent')
                    ->setDescription('Note: For Finalists Page accordion content only')
            )->setTitle('Finalists Page Content'));

            $fields->addFieldToTab('Root.Extra', FieldGroup::create(
                CheckboxField::create('ShowInWinnersPage')
                    ->setDescription('Click to show in Winners Page accordion'),
                HTMLEditorField::create('WinnersPageContent')
                    ->setDescription('Note: For Winners Page accordion content only')
            )->setTitle('Winners Page Content'));

            $fields->addFieldToTab('Root.Extra', FieldGroup::create(
                CheckboxField::create('ShowInGalleryPage')
                    ->setDescription('Click to show in Gallery Page accordion'),
                HTMLEditorField::create('GalleryPageContent')
                    ->setDescription('Note: For Gallery Page accordion content only')
            )->setTitle('Gallery Page Content'));

            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
