<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class EventGallery extends DataObject
    {
        private static $default_sort = 'Sort';

        private static $singular_name = 'Event Gallery';
        private static $plural_name = "Event Galleries";

        private static $db = [
            'Name'      => 'Text',
            'Archived'  => 'Boolean',
            'Sort'      => 'Int'
        ];

        private static $has_one = [
            'Image'     => Image::class,
            'EventYear' => EventYear::class,
        ];

        private static $owns = [
            'Image'
        ];

        private static $summary_fields = [
            'Name',
            'Image.CMSThumbnail' => 'Image',
            'ReadableEventYear'  => 'Year',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('EventYearID', 'Event year',
                EventYear::get()->filter('Archived', false)->map('ID','Name')));
            $fields->addFieldToTab('Root.Main', UploadField::create('Image')
                ->setFolderName('GalleryPage/Images'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }

        public function getReadableEventYear()
        {
            return $this->EventYear()->Name;
        }
    }
}
